<?php

namespace Database\Seeders;

use App\Models\Feriante;
use Illuminate\Database\Seeder;

class FerianteSeeder extends Seeder
{
    /**
     * Carga feriantes de prueba con datos ficticios (decisión D-05).
     *
     * - Todos pueden iniciar sesión con la contraseña "Feriante123".
     * - El primero (feriante@feriaza.test) es el usuario de prueba
     *   documentado en docs/instalacion.md.
     * - Los valores de "rubro" y "estado" respetan exactamente los que
     *   aceptan las validaciones de los controladores.
     */
    public function run(): void
    {
        $feriantes = [
            [
                'nombre'                => 'Feriante',
                'apellido'              => 'De Prueba',
                'email'                 => 'feriante@feriaza.test',
                'telefono'              => '3644100000',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Artesanías de Prueba',
                'instagram'             => '@artesanias.prueba',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'María',
                'apellido'              => 'González',
                'email'                 => 'maria.gonzalez@feriaza.test',
                'telefono'              => '3644101111',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Arte María',
                'instagram'             => '@arte.maria',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'José',
                'apellido'              => 'Suárez',
                'email'                 => 'jose.suarez@feriaza.test',
                'telefono'              => '3644102222',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => null,
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'María José',
                'apellido'              => 'Estévez',
                'email'                 => 'majo.estevez@feriaza.test',
                'telefono'              => '3644103333',
                'rubro'                 => 'masas',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Masas Majo',
                'instagram'             => '@masas.majo',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Laura',
                'apellido'              => 'Carrizo',
                'email'                 => 'laura.carrizo@feriaza.test',
                'telefono'              => '3644104444',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Tejidos Laura',
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Luis',
                'apellido'              => 'Ortiz',
                'email'                 => 'luis.ortiz@feriaza.test',
                'telefono'              => '3644105555',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Vasos Ortiz',
                'instagram'             => '@vasos.ortiz',
                'asistencia_confirmada' => false,
                'estado'                => 'rechazado',
            ],
            [
                'nombre'                => 'Carina',
                'apellido'              => 'Benítez',
                'email'                 => 'carina.benitez@feriaza.test',
                'telefono'              => '3644106666',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Stock Carina',
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Silvia',
                'apellido'              => 'Romero',
                'email'                 => 'silvia.romero@feriaza.test',
                'telefono'              => '3644107777',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Todo Silvia',
                'instagram'             => '@todo.silvia',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Gabriel',
                'apellido'              => 'Sosa',
                'email'                 => 'gabriel.sosa@feriaza.test',
                'telefono'              => '3644108888',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Artesanías Gabriel',
                'instagram'             => '@gabriel.art',
                'asistencia_confirmada' => false,
                'estado'                => 'rechazado',
            ],
            [
                'nombre'                => 'Lucas',
                'apellido'              => 'Medina',
                'email'                 => 'lucas.medina@feriaza.test',
                'telefono'              => '3644109999',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Soldaduras Medina',
                'instagram'             => '@lucas.sold',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Amalia',
                'apellido'              => 'Ferreyra',
                'email'                 => 'amalia.ferreyra@feriaza.test',
                'telefono'              => '3644111110',
                'rubro'                 => 'masas',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Amalia Masas',
                'instagram'             => '@amalia.masitas',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Jeremías',
                'apellido'              => 'Quiroga',
                'email'                 => 'jeremias.quiroga@feriaza.test',
                'telefono'              => '3644112221',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Jere Artesanías',
                'instagram'             => '@jere.artesanias',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Luciana',
                'apellido'              => 'López',
                'email'                 => 'luciana.lopez@feriaza.test',
                'telefono'              => '3644113332',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Luciana Manualidades',
                'instagram'             => '@luciana.manualidades',
                'asistencia_confirmada' => false,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Ignacio',
                'apellido'              => 'Barrios',
                'email'                 => 'ignacio.barrios@feriaza.test',
                'telefono'              => '3644114443',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => null,
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Alicia',
                'apellido'              => 'Llanos',
                'email'                 => 'alicia.llanos@feriaza.test',
                'telefono'              => '3644115554',
                'rubro'                 => 'masas',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Masitas de Alicia',
                'instagram'             => '@alicia.masitas',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Cristina',
                'apellido'              => 'Aguirre',
                'email'                 => 'cristina.aguirre@feriaza.test',
                'telefono'              => '3644116665',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Cris Artesanías',
                'instagram'             => '@cris.artesanias',
                'asistencia_confirmada' => false,
                'estado'                => 'rechazado',
            ],
            [
                'nombre'                => 'Violeta',
                'apellido'              => 'Torres',
                'email'                 => 'violeta.torres@feriaza.test',
                'telefono'              => '3644117776',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Vilu Alhajas',
                'instagram'             => '@vilu.alhajas',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Nicolás',
                'apellido'              => 'Paz',
                'email'                 => 'nicolas.paz@feriaza.test',
                'telefono'              => '3644118887',
                'rubro'                 => 'artesano',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Macetas Nico',
                'instagram'             => '@macetas.nico',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Ruth',
                'apellido'              => 'Pereyra',
                'email'                 => 'ruth.pereyra@feriaza.test',
                'telefono'              => '3644119998',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => null,
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'pendiente',
            ],
            [
                'nombre'                => 'María',
                'apellido'              => 'Zamora',
                'email'                 => 'maria.zamora@feriaza.test',
                'telefono'              => '3644121109',
                'rubro'                 => 'masas',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'María Masas',
                'instagram'             => '@maria.masas',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Carmen',
                'apellido'              => 'Vera',
                'email'                 => 'carmen.vera@feriaza.test',
                'telefono'              => '3644122220',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Joyería Vera',
                'instagram'             => '@joyeria.vera',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Roxana',
                'apellido'              => 'Vega',
                'email'                 => 'roxana.vega@feriaza.test',
                'telefono'              => '3644123331',
                'rubro'                 => 'otro',
                'rubro_otro'            => 'Peluches de tela',
                'nombre_emprendimiento' => 'Peluches Roxy',
                'instagram'             => '@peluches.roxy',
                'asistencia_confirmada' => true,
                'estado'                => 'pendiente',
            ],
            [
                'nombre'                => 'Patricio',
                'apellido'              => 'Juárez',
                'email'                 => 'patricio.juarez@feriaza.test',
                'telefono'              => '3644124442',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => null,
                'instagram'             => null,
                'asistencia_confirmada' => false,
                'estado'                => 'rechazado',
            ],
            [
                'nombre'                => 'Leonel',
                'apellido'              => 'Acosta',
                'email'                 => 'leonel.acosta@feriaza.test',
                'telefono'              => '3644125553',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Leo Manualidades',
                'instagram'             => '@leo.manualidades',
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
            [
                'nombre'                => 'Nora',
                'apellido'              => 'Maldonado',
                'email'                 => 'nora.maldonado@feriaza.test',
                'telefono'              => '3644126664',
                'rubro'                 => 'revendedor',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => 'Nora Bazar',
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'pendiente',
            ],
            [
                'nombre'                => 'Florencia',
                'apellido'              => 'Molina',
                'email'                 => 'florencia.molina@feriaza.test',
                'telefono'              => '3644127775',
                'rubro'                 => 'manualidades',
                'rubro_otro'            => null,
                'nombre_emprendimiento' => null,
                'instagram'             => null,
                'asistencia_confirmada' => true,
                'estado'                => 'aprobado',
            ],
        ];

        foreach ($feriantes as $datos) {
            // updateOrCreate: si el seeder se ejecuta de nuevo, no duplica feriantes.
            // La contraseña se hashea sola por el cast 'hashed' del modelo Feriante.
            Feriante::updateOrCreate(
                ['email' => $datos['email']],
                $datos + ['password' => 'Feriante123']
            );
        }
    }
}
